#!/usr/bin/env python3
"""
Regenerate src/site/favicon.ico and the base64 module the Worker serves.

Pure stdlib — writes the PNG by hand and wraps it in an ICO container, so there is
no image dependency to install. Run after changing the brand colours.

    python3 scripts/make-favicon.py
"""
import base64
import pathlib
import struct
import zlib

W = H = 32
BG = (0x0A, 0x0A, 0x0A, 255)  # page background
FG = (0x00, 0xC8, 0x96, 255)  # page accent

px = [[BG for _ in range(W)] for _ in range(H)]


def vline(x, y0, y1, w=3):
    for y in range(y0, y1 + 1):
        for d in range(w):
            if 0 <= x + d < W:
                px[y][x + d] = FG


def hline(y, x0, x1, h=3):
    for x in range(x0, x1 + 1):
        for d in range(h):
            if 0 <= y + d < H:
                px[y + d][x] = FG


# Naira mark: two uprights, a diagonal, two crossbars. Plotted by hand so it stays
# legible once a browser downscales it to 16x16.
TOP, BOT = 6, 25
vline(7, TOP, BOT)
vline(22, TOP, BOT)
for i in range(BOT - TOP + 1):
    x = 7 + round(i * (22 - 7) / (BOT - TOP))
    for d in range(3):
        if 0 <= x + d < W:
            px[TOP + i][x + d] = FG
hline(13, 3, 28)
hline(18, 3, 28)

raw = b"".join(b"\x00" + b"".join(bytes(px[y][x]) for x in range(W)) for y in range(H))


def chunk(tag, data):
    return (
        struct.pack(">I", len(data))
        + tag
        + data
        + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    )


png = (
    b"\x89PNG\r\n\x1a\n"
    + chunk(b"IHDR", struct.pack(">IIBBBBB", W, H, 8, 6, 0, 0, 0))
    + chunk(b"IDAT", zlib.compress(raw, 9))
    + chunk(b"IEND", b"")
)

ico = struct.pack("<HHH", 0, 1, 1) + struct.pack(
    "<BBBBHHII", W, H, 0, 0, 1, 32, len(png), 22
) + png

root = pathlib.Path(__file__).resolve().parent.parent
(root / "src/site/favicon.ico").write_bytes(ico)
(root / "src/site/favicon.ts").write_text(
    "/**\n"
    " * 32x32 favicon, base64-encoded.\n"
    " *\n"
    " * Embedded as a string rather than imported as a binary asset so it needs no\n"
    " * wrangler Data rule — module rules replace wrangler defaults rather than adding\n"
    " * to them, and one such rule already carries the HTML import.\n"
    " *\n"
    " * Generated by scripts/make-favicon.py. Do not edit by hand.\n"
    " */\n"
    "export const FAVICON_ICO_BASE64 =\n  '%s'\n" % base64.b64encode(ico).decode()
)
print("wrote favicon.ico (%d bytes) and favicon.ts" % len(ico))
