/**
 * 32x32 favicon, base64-encoded.
 *
 * Embedded as a string rather than imported as a binary asset so it needs no
 * wrangler Data rule — module rules replace wrangler defaults rather than adding
 * to them, and one such rule already carries the HTML import.
 *
 * Generated by scripts/make-favicon.py. Do not edit by hand.
 */
export const FAVICON_ICO_BASE64 =
  'AAABAAEAICAAAAEAIACkAAAAFgAAAIlQTkcNChoKAAAADUlIRFIAAAAgAAAAIAgGAAAAc3p69AAAAGtJREFUeNrt1jEKACAMA8DO/T++yV/p5qY0kqJohk5qOSSUmru3k2UCCHA1wGoZBTcOvg0DUEQKAEG8C4gi6AA0lCkAqPEOYPbl7BKANglX52khjN5RCP8IIWN00/cBAdBF5u6VTFuxAF8AOj33w0zCwzUgAAAAAElFTkSuQmCC'
